FROM python:3.13-slim

RUN useradd -m -s /bin/bash chat-bot

WORKDIR /app

COPY deploy/req/api.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc libpq-dev \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY src/ /app/src/
COPY .env /app/.env
COPY .dockerignore /app/.dockerignore
COPY alembic.ini /app/alembic.ini
COPY deploy/entrypoints/api.sh /app/entrypoint.sh

ENV PYTHONPATH=/app/
RUN chmod +x /app/entrypoint.sh

USER chat-bot

ENTRYPOINT ["/app/entrypoint.sh"]
