apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-chatbot-config
  namespace: ai-chatbot
data:
  API_INNER_PORT: "8001"
  API_OUTER_PORT: "8001"
  API_WORKERS_AMOUNT: "1"
  POSTGRES_USER: "..."
  POSTGRES_PASSWORD: "..."
  POSTGRES_DB: "..."
  POSTGRES_HOST: "postgres-service"
  INNER_POSTGRES_PORT: "5432"
  OUTER_POSTGRES_PORT: "5433"
  REDIS_HOST: "redis-service"
  INNER_REDIS_PORT: "6379"
  OUTER_REDIS_PORT: "6379"
  REDIS_USER: "..."
  REDIS_PASSWORD: "..."
  CHATGPT_API_KEY: "..."
  GROQ_API_KEY: "..."
