secret:
  create: true
  name: ai-chatbot-secrets

env:
  secrets:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_DB: "chatbot"
    REDIS_USER: "default"
    REDIS_PASSWORD: "changeme"
    CHATGPT_API_KEY: "your-chatgpt-api-key"
    GROQ_API_KEY: "your-groq-api-key"
