{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "ai-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.env.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
