#!/bin/sh
redis-cli -a ${REDIS_PASSWORD} ACL SETUSER ${REDIS_USER} on ">"${REDIS_PASSWORD} ~* +@all
redis-cli -a ${REDIS_PASSWORD} FT.CREATE qa_vectors ON HASH PREFIX 1 q: SCHEMA embedding VECTOR FLAT 6 TYPE FLOAT32 DIM 384 DISTANCE_METRIC COSINE
